### ISSUE TITLE
$ref with url encoded symbols doesn't work

### ISSUE THREAD

**Issue by RomanGotsiy** [Mermade/swagger2openapi#41] opened 2017-11-28 08:55 UTC
### Checklist
- [x] I have checked my source definition is valid OpenAPI 2.0

### Detailed Description
As far as I understand from [this comment](https://github.com/BigstickCarpet/json-schema-ref-parser/issues/44#issuecomment-318471923) `$ref` may be uri-encoded. I'm handling this in ReDoc by using `decodeURI` whenever resolving a pointer.

But the following spec crashes when converting with `swagger2openapi`:

```yaml
---
swagger: '2.0'
info:
  title: Test
  version: ''
paths:
  "/test":
    get:
      responses:
        '200':
          description: OK
          schema:
            "$ref": "#/definitions/Def%20with%20space"
definitions:
  Def with space:
    type: string
```
with the following error message:

```
status: false
message: 'Could not resolve reference #/definitions/Def%20with%20space'
```

**Comment by MikeRalphson** [comment] 2017-11-28 09:21
Just running CI checks now.

**Comment by MikeRalphson** [comment] 2017-11-28 09:34
Should be fixed in swagger2openapi@2.11.7

**Comment by RomanGotsiy** [comment] 2017-11-28 10:02
@MikeRalphson fast as usual! 🚅 
Thanks!

**Comment by MikeRalphson** [comment] 2017-11-28 10:06
The problem is I add the bugs just as fast. :(

Please chase if any further problems on this issue.

**Closed by MikeRalphson** 2017-11-28 10:06 UTC
Labels: bug
